export interface Artwork {
  "150x150": string;
  "480x480": string;
  "1000x1000": string;
}

export interface PlaylistContent {
  metadata_timestamp: string | null;
  timestamp: string | null;
  track_id: string | null;
}

export interface User {
  album_count: number;
  artist_pick_track_id: string | null;
  bio: string;
  cover_photo: {
    "640x"?: string | null;
    "2000x"?: string | null;
  } | null;
  followee_count: number;
  follower_count: number;
  handle: string;
  id: string;
  is_verified: boolean;
  twitter_handle: string | null;
  instagram_handle: string | null;
  tiktok_handle: string | null;
  verified_with_twitter: boolean;
  verified_with_instagram: boolean;
  verified_with_tiktok: boolean;
  website: string | null;
  donation: string | null;
  location: string;
  name: string;
  playlist_count: number;
  profile_picture: Artwork;
  repost_count: number;
  track_count: number;
  is_deactivated: boolean;
  is_available: boolean;
  erc_wallet: string;
  spl_wallet: string;
  supporter_count: number;
  supporting_count: number;
  total_audio_balance: number;
  wallet: string;
}

export interface Playlist {
  artwork: Artwork;
  description: string;
  permalink: string;
  id: string;
  is_album: boolean;
  is_image_autogenerated: boolean;
  playlist_name: string;
  playlist_contents: PlaylistContent[];
  repost_count: number;
  favorite_count: number;
  total_play_count: number;
  user: User;
  ddex_app: string | null;
  access: {
    stream: boolean;
    download: boolean;
  };
  upc: string | null;
  track_count: number;
}

export interface PlaylistResponse {
  data: Playlist[];
}
